version: "3.9"

services:
  db:
    image: mariadb:10.5
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  web:
    build: .
    volumes:
      - .:/code
    environment:
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DEBUG
      - SECRET_KEY
      - ALLOWED_HOSTS
    depends_on:
      - db