version: "3.9"

services:
  web:
    command: "sh -c /code/init.prod.sh"
    environment:
      - DEBUG=on
    volumes:
      - static_volume:/code/static
    expose:
      - 8000

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
