# Generated by Django 3.2 on 2021-04-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passman', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password',
            options={'ordering': ('username', 'url'), 'verbose_name': 'password', 'verbose_name_plural': 'passwords'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('name',), 'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
    ]
